SELECT
	CHILDREN.NAME,
	WISH_LISTS.WISHES ->> 'first_choice' AS PRIMARY_WISH,
	WISH_LISTS.WISHES ->> 'second_choice' AS BACKUP_WISH,
	WISH_LISTS.WISHES #>> '{colors, 0}' AS FAVORITE_COLOR,
	JSON_ARRAY_LENGTH(WISH_LISTS.WISHES -> 'colors') AS COLOR_COUNT,
	CASE
		WHEN DIFFICULTY_TO_MAKE = 1 THEN 'Simple Gift'
		WHEN DIFFICULTY_TO_MAKE = 2 THEN 'Moderate Gift'
		WHEN DIFFICULTY_TO_MAKE >= 3 THEN 'Complex Gift'
	END AS GIFT_COMPLEXITY,
	CASE
		WHEN CATEGORY = 'outdoor' THEN 'Outside Workshop'
		WHEN CATEGORY = 'educational' THEN 'Learning Workshop'
		ELSE 'General Workshop'
	END AS WORKSHOP_ASSIGNMENT
FROM
	WISH_LISTS
	JOIN CHILDREN ON CHILDREN.CHILD_ID = WISH_LISTS.CHILD_ID
	JOIN TOY_CATALOGUE ON WISH_LISTS.WISHES ->> 'first_choice' = TOY_CATALOGUE.TOY_NAME
ORDER BY
	CHILDREN.NAME
LIMIT
	5;