SELECT
	string_agg(DECODED_MESSAGE::text, '')
FROM
	(
		SELECT
			DECODED_MESSAGE
		FROM
			(
				SELECT
					CASE
						WHEN VALUE BETWEEN 97 AND 122  THEN CHR(VALUE)
						WHEN VALUE BETWEEN 65 AND 90  THEN CHR(VALUE)
						WHEN VALUE = 32 THEN CHR(VALUE)
						WHEN VALUE = 33 THEN CHR(VALUE) -- !
						WHEN VALUE = 34 THEN CHR(VALUE) -- "
						WHEN VALUE = 39 THEN CHR(VALUE) -- '
						WHEN VALUE BETWEEN 40 AND 41  THEN CHR(VALUE) -- ()
						WHEN VALUE = 44 THEN CHR(VALUE) -- ,
						WHEN VALUE = 45 THEN CHR(VALUE) -- -
						WHEN VALUE = 46 THEN CHR(VALUE) -- .
						WHEN VALUE BETWEEN 58 AND 59  THEN CHR(VALUE) -- :;
						WHEN VALUE = 63 THEN CHR(VALUE) -- ?
					END AS DECODED_MESSAGE
				FROM
					LETTERS_A
			) AS DECODED_MESSAGE
		WHERE
			DECODED_MESSAGE IS NOT NULL
		UNION ALL
		SELECT
			DECODED_MESSAGE
		FROM
			(
				SELECT
					CASE
						WHEN VALUE BETWEEN 97 AND 122  THEN CHR(VALUE)
						WHEN VALUE BETWEEN 65 AND 90  THEN CHR(VALUE)
						WHEN VALUE = 32 THEN CHR(VALUE)
						WHEN VALUE = 33 THEN CHR(VALUE) -- !
						WHEN VALUE = 34 THEN CHR(VALUE) -- "
						WHEN VALUE = 39 THEN CHR(VALUE) -- '
						WHEN VALUE BETWEEN 40 AND 41  THEN CHR(VALUE) -- ()
						WHEN VALUE = 44 THEN CHR(VALUE) -- ,
						WHEN VALUE = 45 THEN CHR(VALUE) -- -
						WHEN VALUE = 46 THEN CHR(VALUE) -- .
						WHEN VALUE BETWEEN 58 AND 59  THEN CHR(VALUE) -- :;
						WHEN VALUE = 63 THEN CHR(VALUE) -- ?
					END AS DECODED_MESSAGE
				FROM
					LETTERS_B
			) AS DECODED_MESSAGE
		WHERE
			DECODED_MESSAGE IS NOT NULL
	) as DECODED_MESSAGE;